import type { AnalysisResult } from '@/types';
import { getScoreLabel } from '@/engine/scoring';

/**
 * Trigger a file download in the browser.
 */
function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Export analysis result as JSON.
 */
export function exportAsJSON(result: AnalysisResult, text: string): void {
  const data = {
    generatedAt: new Date().toISOString(),
    tool: 'Humanize',
    version: '1.1.0',
    input: { text, wordCount: result.stats.wordCount },
    score: result.score,
    scoreLabel: getScoreLabel(result.score),
    counts: result.counts,
    stats: {
      wordCount: result.stats.wordCount,
      sentenceCount: result.stats.sentenceCount,
      paragraphCount: result.stats.paragraphCount,
      avgSentenceLength: result.stats.avgSentenceLength,
      coefficientOfVariation: result.stats.coefficientOfVariation,
    },
    issues: result.issues,
    highlights: result.highlights.map((h) => ({
      type: h.type,
      text: h.text,
      tip: h.tip,
      position: { start: h.start, end: h.end },
    })),
  };
  downloadFile(JSON.stringify(data, null, 2), 'humanize-report.json', 'application/json');
}

/**
 * Build a Markdown report string from analysis results.
 * Exported separately for testing.
 */
export function buildMarkdownReport(result: AnalysisResult, text: string): string {
  const lines: string[] = [];

  lines.push('# Humanize Diagnostic Report');
  lines.push('');
  lines.push(`**Score:** ${result.score}/100 (${getScoreLabel(result.score)})`);
  lines.push(
    `**Words:** ${result.stats.wordCount} | **Sentences:** ${result.stats.sentenceCount} | **Sentence variation:** ${result.stats.coefficientOfVariation.toFixed(2)}`,
  );
  lines.push('');

  // Issues
  if (result.issues.length > 0) {
    lines.push('## Issues Found');
    lines.push('');

    const bySeverity = { high: [] as typeof result.issues, medium: [] as typeof result.issues, low: [] as typeof result.issues };
    for (const issue of result.issues) {
      bySeverity[issue.severity].push(issue);
    }

    for (const [severity, issues] of Object.entries(bySeverity)) {
      if (issues.length === 0) continue;
      const label = severity === 'high' ? 'High' : severity === 'medium' ? 'Medium' : 'Low';
      lines.push(`### ${label} Severity`);
      lines.push('');
      for (const issue of issues) {
        lines.push(`- **${issue.title}** — ${issue.suggestion}`);
      }
      lines.push('');
    }
  }

  // Pattern breakdown
  lines.push('## Pattern Breakdown');
  lines.push('');
  lines.push('| Category | Count |');
  lines.push('|----------|-------|');
  lines.push(`| Filler | ${result.counts.filler} |`);
  lines.push(`| Hedge | ${result.counts.hedge} |`);
  lines.push(`| Connector | ${result.counts.connector} |`);
  lines.push(`| Template | ${result.counts.template} |`);
  lines.push(`| Passive | ${result.counts.passive} |`);
  lines.push('');

  // Highlighted patterns (first 30)
  if (result.highlights.length > 0) {
    lines.push('## Highlighted Patterns');
    lines.push('');
    const shown = result.highlights.slice(0, 30);
    for (const h of shown) {
      lines.push(`- [${h.type}] "${h.text}" — ${h.tip}`);
    }
    if (result.highlights.length > 30) {
      lines.push(`- ... and ${result.highlights.length - 30} more`);
    }
    lines.push('');
  }

  // Input text (truncated)
  lines.push('## Analyzed Text');
  lines.push('');
  const truncated = text.length > 2000 ? text.slice(0, 2000) + '\n\n[... truncated]' : text;
  lines.push('```');
  lines.push(truncated);
  lines.push('```');
  lines.push('');
  lines.push('---');
  lines.push('*Generated by [Humanize](https://github.com/) — AI text diagnostic tool*');

  return lines.join('\n');
}

/**
 * Export analysis result as Markdown.
 */
export function exportAsMarkdown(result: AnalysisResult, text: string): void {
  const markdown = buildMarkdownReport(result, text);
  downloadFile(markdown, 'humanize-report.md', 'text/markdown');
}
