// Auto-generated by scripts/buildPresets.mjs — DO NOT EDIT
// To populate: place PDFs in papers/<venue>/ and run `node scripts/buildPresets.mjs`
import type { StyleProfile } from '@/types';

export interface BuiltinPreset {
  id: string;
  venue: string;
  label: string;
  profile: StyleProfile;
  sourceFiles: string[];
  paperCount: number;
}

/** Built-in style presets (empty until you run the build script) */
export const BUILTIN_PRESETS: BuiltinPreset[] = [];
